version: "3"
services:
  vulnado:
    build: .
    ports:
      - 8080:8080
    links:
      - db
      - internal_site
    environment:
      - PGPASSWORD=vulnado
      
    depends_on:
      - "db"

  client:
    build: client
    ports:
      - 1337:80

  internal_site:
    build: internal_site
